name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    strategy:
      matrix:
        smo:
          - {S2VER: 100, S2VERSTR: 1.0.0}
          - {S2VER: 130, S2VERSTR: 1.3.0}
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install python3-pip -y
          python3 -m pip install -U setuptools
          python3 -m pip install -U keystone-engine
      - name: Build
        run: |
          make S2VER=${{ matrix.smo.S2VER }} S2VERSTR=${{ matrix.smo.S2VERSTR }}
